ALTER TABLE "BINARIES" ADD COLUMN "BIN_HASH" BINARY(32);
UPDATE "BINARIES" SET "BIN_HASH" = (SELECT (CAST("BIN_ID" AS BINARY(32))));
ALTER TABLE "BINARIES" ALTER COLUMN "BIN_HASH" SET NOT NULL;
ALTER TABLE "BINARIES_CONTENTS" ALTER COLUMN "BIN_ID" RENAME TO "BIN_HASH";
ALTER TABLE "BINARIES_CONTENTS" ALTER COLUMN "BIN_HASH" BINARY(32) NOT NULL;
