CREATE TABLE BINARIES_CONTENTS (
  BIN_ID       BIGINT             NOT NULL PRIMARY KEY,
  `BINARY`     LONGBLOB           NOT NULL
);

INSERT INTO BINARIES_CONTENTS (BIN_ID, `BINARY`) SELECT BIN_ID, `BINARY` FROM BINARIES;

ALTER TABLE BINARIES DROP COLUMN `BINARY`;
