version: 2

jobs:
  build:
    working_directory: /app
    docker:

      - image: hyperanna1/docker-base:latest

      # https://hub.docker.com/r/codestar/circleci-scala-sbt-git/tags/
      #codestar/circleci-scala-sbt-git:scala-2.11.11-sbt-0.13.15
      #docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv -n /tmp/docker/* /usr/bin

#      - restore_cache:
#          keys:
#            - v1-{{ .Branch }}
#          paths:
#            - /caches/app.tar
#      - run:
#          name: Load Docker image layer cache
#          command: |
#            set +o pipefail
#            docker load -i /caches/app.tar | true

      - run:
          command: sbt sbtVersion

      - run:
          # TODO: For some reason circleci gets stuck in the shell if we don't add exit to sbt
          command: |
            sbt compile exit

#      - run:
#          command:
#            sbt test exit

      - run:
          name: Build application Docker image
          command: |
            sbt docker
#            docker build --cache-from=hyperanna1/${CIRCLE_PROJECT_REPONAME}:cache -t hyperanna1/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} .
#      - run:
#          name: Save Docker image layer cache
#          command: |
#            mkdir -p /caches
#            docker tag hyperanna1/${CIRCLE_PROJECT_REPONAME}:${JOBSEVER_BRANCH} hyperanna1/${CIRCLE_PROJECT_REPONAME}:cache
#            docker save -o /caches/app.tar hyperanna1/${CIRCLE_PROJECT_REPONAME}:cache
#      - save_cache:
#          key: v1-{{ .Branch }}-{{ epoch }}
#          paths:
#            - /caches/app.tar
      - deploy:
          name: Push application Docker image
          timeout: 1200
          command: |
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            docker push hyperanna1/${CIRCLE_PROJECT_REPONAME}:${JOBSEVER_BRANCH}

            docker login dockerhub.hyperanna.com -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            docker tag hyperanna1/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} dockerhub.hyperanna.com/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
            docker push dockerhub.hyperanna.com/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
            
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag hyperanna1/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} hyperanna1/${CIRCLE_PROJECT_REPONAME}:latest
              docker tag hyperanna1/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} hyperanna1/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BUILD_NUM}
              docker push hyperanna1/${CIRCLE_PROJECT_REPONAME}:latest
              docker push hyperanna1/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BUILD_NUM}

              docker tag hyperanna1/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} dockerhub.hyperanna.com/${CIRCLE_PROJECT_REPONAME}:latest
              docker tag hyperanna1/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} dockerhub.hyperanna.com/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BUILD_NUM}
              docker push dockerhub.hyperanna.com/${CIRCLE_PROJECT_REPONAME}:latest
              docker push dockerhub.hyperanna.com/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BUILD_NUM}
            fi