version: 2

jobs:
  build:
    environment:
      SBT_VERSION: 0.13.15
      # REDIS_URL: redis://localhost:6391
    java:
      version: oraclejdk8
    services:
      - redis      # this will use the default Redis 2.8.4

    ## Customize dependencies
    dependencies:
      pre:
        - sbt about
      override:
        - sbt update

    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true

      - run: cat /dev/null | sbt test:compile

#      - run:
#          name: Build application Docker image
#          command: |
#            docker build --cache-from=hyperanna1/${CIRCLE_PROJECT_REPONAME}:cache -t hyperanna1/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker tag hyperanna1/spark-jobserver:0.8.0-SNAPSHOT.mesos-1.0.0.spark-2.2.0.scala-2.11.jdk-8-jdk hyperanna1/${CIRCLE_PROJECT_REPONAME}:cache
            docker save -o /caches/app.tar hyperanna1/${CIRCLE_PROJECT_REPONAME}:cache
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - deploy:
          name: Push application Docker image
          timeout: 1200
          command: |
            docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
            docker push hyperanna1/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag hyperanna1/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH} hyperanna1/${CIRCLE_PROJECT_REPONAME}:latest
              docker push hyperanna1/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}
              docker push hyperanna1/${CIRCLE_PROJECT_REPONAME}:latest
            fi