FROM openjdk:8-jdk

USER root

# install and cache sbt, python
RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list && \
    curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add && \
    apt-get -qq update && \
    apt-get install -y --force-yes python3 python3-pip sbt=1.1.6

WORKDIR /usr/src/app/

# install other ci deps
COPY ci ci
RUN ci/install-python-dependencies.sh && \
    ci/install-spark.sh

# add sbt and cache deps
COPY project project
COPY build.sbt .
RUN sbt update

# add the rest of the code
COPY . .

ENV SPARK_HOME /tmp/spark-2.4.4-bin-hadoop2.7
ENV JAVA_OPTIONS "-Xmx1500m -Dakka.test.timefactor=3"

CMD ["/usr/src/app/run_tests.sh"]
