CREATE TABLE BINARIES (
  BIN_ID       BIGINT             AUTO_INCREMENT NOT NULL PRIMARY KEY,
  APP_NAME     VARCHAR(255)       NOT NULL,
  BINARY_TYPE  VARCHAR(255)       NOT NULL,
  UPLOAD_TIME  TIMESTAMP          NOT NULL,
  BIN_HASH     VARBINARY(32)      NOT NULL
);

CREATE TABLE JOBS (
  JOB_ID              VARCHAR(255)    NOT NULL PRIMARY KEY,
  CONTEXT_ID          VARCHAR(255)    NOT NULL,
  CONTEXT_NAME        VARCHAR(255)    NOT NULL,
  BIN_ID              INTEGER         NOT NULL,
  CLASSPATH           VARCHAR(255)    NOT NULL,
  STATE               VARCHAR(255)    NOT NULL,
  START_TIME          TIMESTAMP,
  END_TIME            TIMESTAMP,
  ERROR               CLOB,
  ERROR_CLASS         VARCHAR(255),
  ERROR_STACK_TRACE   CLOB
);

CREATE TABLE CONFIGS (
  JOB_ID      VARCHAR(255)        NOT NULL PRIMARY KEY,
  JOB_CONFIG     CLOB             NOT NULL
);

CREATE TABLE CONTEXTS (
  ID                    VARCHAR(255)    NOT NULL PRIMARY KEY,
  NAME                  VARCHAR(255)    NOT NULL,
  CONFIG                CLOB            NOT NULL,
  ACTOR_ADDRESS         VARCHAR(255),
  START_TIME            TIMESTAMP       NOT NULL,
  END_TIME              TIMESTAMP,
  STATE                 VARCHAR(255)    NOT NULL,
  ERROR                 CLOB
);

CREATE TABLE BLOBS (
  BIN_ID       VARCHAR(255)       NOT NULL PRIMARY KEY,
  BINARY       BYTEA              NOT NULL
);