CREATE TABLE "BINARIES_CONTENTS" (
  "BIN_ID"          SERIAL                        NOT NULL PRIMARY KEY,
  "BINARY"          BYTEA                         NOT NULL
);

INSERT INTO "BINARIES_CONTENTS" ("BIN_ID", "BINARY") SELECT "BIN_ID", "BINARY" FROM "BINARIES";

ALTER TABLE "BINARIES" DROP COLUMN "BINARY";
