ALTER TABLE `JARS` RENAME TO `BINARIES`;
ALTER TABLE `BINARIES` CHANGE COLUMN `JAR` `BINARY` LONGBLOB;
ALTER TABLE `BINARIES` CHANGE COLUMN `JAR_ID` `BIN_ID` SERIAL NOT NULL;
ALTER TABLE `BINARIES` ADD COLUMN `BINARY_TYPE` VARCHAR(10) NOT NULL;
UPDATE `BINARIES` SET `BINARY_TYPE` = 'Jar';
ALTER TABLE `JOBS` CHANGE COLUMN `JAR_ID` `BIN_ID` INTEGER NOT NULL;
