ALTER TABLE JARS RENAME TO BINARIES;
ALTER TABLE BINARIES ALTER COLUMN JAR RENAME TO BINARY;
ALTER TABLE BINARIES ALTER COLUMN JAR_ID RENAME TO BIN_ID;
ALTER TABLE BINARIES ADD COLUMN BINARY_TYPE VARCHAR(10);
UPDATE BINARIES SET BINARY_TYPE = 'Jar';
ALTER TABLE BINARIES ALTER COLUMN BINARY_TYPE SET NOT NULL;
ALTER TABLE JOBS ALTER COLUMN JAR_ID RENAME TO BIN_ID;
