ALTER TABLE "JARS" RENAME TO "BINARIES";
ALTER TABLE "BINARIES" RENAME COLUMN "JAR" TO "BINARY";
ALTER TABLE "BINARIES" RENAME "JAR_ID" TO "BIN_ID";
ALTER TABLE "BINARIES" ADD COLUMN "BINARY_TYPE" VARCHAR(10);
UPDATE "BINARIES" SET "BINARY_TYPE" = 'Jar';
ALTER TABLE "BINARIES" ALTER COLUMN "BINARY_TYPE" SET NOT NULL;
ALTER TABLE "JOBS" RENAME "JAR_ID" TO "BIN_ID";
