ALTER TABLE "BINARIES" ADD COLUMN "BIN_HASH" BYTEA;
UPDATE "BINARIES" SET "BIN_HASH" = (SELECT "BIN_ID"::VARCHAR(32)::BYTEA);
ALTER TABLE "BINARIES" ALTER COLUMN "BIN_HASH" SET NOT NULL;
ALTER TABLE "BINARIES_CONTENTS" ADD COLUMN "BIN_HASH" BYTEA;
UPDATE "BINARIES_CONTENTS" SET "BIN_HASH" = (SELECT "BIN_ID"::VARCHAR(32)::BYTEA);
ALTER TABLE "BINARIES_CONTENTS" ALTER COLUMN "BIN_HASH" SET NOT NULL;
ALTER TABLE "BINARIES_CONTENTS" DROP COLUMN "BIN_ID";
ALTER TABLE "BINARIES_CONTENTS" ADD PRIMARY KEY ("BIN_HASH");
