ALTER TABLE `BINARIES` ADD COLUMN `BIN_HASH` VARBINARY(32) NOT NULL;
UPDATE `BINARIES` SET `BIN_HASH` = (SELECT CAST(`BIN_ID` AS BINARY(32)));
ALTER TABLE `BINARIES_CONTENTS` CHANGE COLUMN `BIN_ID` `BIN_HASH` VARBINARY(32) NOT NULL;
